/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedValidationRouteImport } from './routes/_authenticated/validation'
import { Route as AuthenticatedSwotRouteImport } from './routes/_authenticated/swot'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedManagerResultsRouteImport } from './routes/_authenticated/manager.results'
import { Route as AuthenticatedManagerConsolidateRouteImport } from './routes/_authenticated/manager.consolidate'
import { Route as AuthenticatedManagerCompileRouteImport } from './routes/_authenticated/manager.compile'
import { Route as AuthenticatedManagerAnalyticsRouteImport } from './routes/_authenticated/manager.analytics'
import { Route as AuthenticatedManagerActionPlanRouteImport } from './routes/_authenticated/manager.action-plan'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValidationRoute = AuthenticatedValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSwotRoute = AuthenticatedSwotRouteImport.update({
  id: '/swot',
  path: '/swot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerResultsRoute =
  AuthenticatedManagerResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerConsolidateRoute =
  AuthenticatedManagerConsolidateRouteImport.update({
    id: '/consolidate',
    path: '/consolidate',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerCompileRoute =
  AuthenticatedManagerCompileRouteImport.update({
    id: '/compile',
    path: '/compile',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerAnalyticsRoute =
  AuthenticatedManagerAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerActionPlanRoute =
  AuthenticatedManagerActionPlanRouteImport.update({
    id: '/action-plan',
    path: '/action-plan',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/manager': typeof AuthenticatedManagerRouteWithChildren
  '/swot': typeof AuthenticatedSwotRoute
  '/validation': typeof AuthenticatedValidationRoute
  '/manager/action-plan': typeof AuthenticatedManagerActionPlanRoute
  '/manager/analytics': typeof AuthenticatedManagerAnalyticsRoute
  '/manager/compile': typeof AuthenticatedManagerCompileRoute
  '/manager/consolidate': typeof AuthenticatedManagerConsolidateRoute
  '/manager/results': typeof AuthenticatedManagerResultsRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/swot': typeof AuthenticatedSwotRoute
  '/validation': typeof AuthenticatedValidationRoute
  '/manager/action-plan': typeof AuthenticatedManagerActionPlanRoute
  '/manager/analytics': typeof AuthenticatedManagerAnalyticsRoute
  '/manager/compile': typeof AuthenticatedManagerCompileRoute
  '/manager/consolidate': typeof AuthenticatedManagerConsolidateRoute
  '/manager/results': typeof AuthenticatedManagerResultsRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRouteWithChildren
  '/_authenticated/swot': typeof AuthenticatedSwotRoute
  '/_authenticated/validation': typeof AuthenticatedValidationRoute
  '/_authenticated/manager/action-plan': typeof AuthenticatedManagerActionPlanRoute
  '/_authenticated/manager/analytics': typeof AuthenticatedManagerAnalyticsRoute
  '/_authenticated/manager/compile': typeof AuthenticatedManagerCompileRoute
  '/_authenticated/manager/consolidate': typeof AuthenticatedManagerConsolidateRoute
  '/_authenticated/manager/results': typeof AuthenticatedManagerResultsRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/manager'
    | '/swot'
    | '/validation'
    | '/manager/action-plan'
    | '/manager/analytics'
    | '/manager/compile'
    | '/manager/consolidate'
    | '/manager/results'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/swot'
    | '/validation'
    | '/manager/action-plan'
    | '/manager/analytics'
    | '/manager/compile'
    | '/manager/consolidate'
    | '/manager/results'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/manager'
    | '/_authenticated/swot'
    | '/_authenticated/validation'
    | '/_authenticated/manager/action-plan'
    | '/_authenticated/manager/analytics'
    | '/_authenticated/manager/compile'
    | '/_authenticated/manager/consolidate'
    | '/_authenticated/manager/results'
    | '/_authenticated/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/validation': {
      id: '/_authenticated/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof AuthenticatedValidationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/swot': {
      id: '/_authenticated/swot'
      path: '/swot'
      fullPath: '/swot'
      preLoaderRoute: typeof AuthenticatedSwotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/results': {
      id: '/_authenticated/manager/results'
      path: '/results'
      fullPath: '/manager/results'
      preLoaderRoute: typeof AuthenticatedManagerResultsRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/consolidate': {
      id: '/_authenticated/manager/consolidate'
      path: '/consolidate'
      fullPath: '/manager/consolidate'
      preLoaderRoute: typeof AuthenticatedManagerConsolidateRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/compile': {
      id: '/_authenticated/manager/compile'
      path: '/compile'
      fullPath: '/manager/compile'
      preLoaderRoute: typeof AuthenticatedManagerCompileRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/analytics': {
      id: '/_authenticated/manager/analytics'
      path: '/analytics'
      fullPath: '/manager/analytics'
      preLoaderRoute: typeof AuthenticatedManagerAnalyticsRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/action-plan': {
      id: '/_authenticated/manager/action-plan'
      path: '/action-plan'
      fullPath: '/manager/action-plan'
      preLoaderRoute: typeof AuthenticatedManagerActionPlanRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
  }
}

interface AuthenticatedManagerRouteChildren {
  AuthenticatedManagerActionPlanRoute: typeof AuthenticatedManagerActionPlanRoute
  AuthenticatedManagerAnalyticsRoute: typeof AuthenticatedManagerAnalyticsRoute
  AuthenticatedManagerCompileRoute: typeof AuthenticatedManagerCompileRoute
  AuthenticatedManagerConsolidateRoute: typeof AuthenticatedManagerConsolidateRoute
  AuthenticatedManagerResultsRoute: typeof AuthenticatedManagerResultsRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
}

const AuthenticatedManagerRouteChildren: AuthenticatedManagerRouteChildren = {
  AuthenticatedManagerActionPlanRoute: AuthenticatedManagerActionPlanRoute,
  AuthenticatedManagerAnalyticsRoute: AuthenticatedManagerAnalyticsRoute,
  AuthenticatedManagerCompileRoute: AuthenticatedManagerCompileRoute,
  AuthenticatedManagerConsolidateRoute: AuthenticatedManagerConsolidateRoute,
  AuthenticatedManagerResultsRoute: AuthenticatedManagerResultsRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
}

const AuthenticatedManagerRouteWithChildren =
  AuthenticatedManagerRoute._addFileChildren(AuthenticatedManagerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRouteWithChildren
  AuthenticatedSwotRoute: typeof AuthenticatedSwotRoute
  AuthenticatedValidationRoute: typeof AuthenticatedValidationRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRouteWithChildren,
  AuthenticatedSwotRoute: AuthenticatedSwotRoute,
  AuthenticatedValidationRoute: AuthenticatedValidationRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
